---
title: "Lab 00 - Hello IDS!"
author: "INSERT YOUR NAME HERE"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Alice", "Dylan", "neo", 
           "Ethan", "Griffin"),
  github_username = c("Alicelilwall", "dylanglen4312", "neoravenevans", 
                      "ethan38carter", "Grifffiin"), 
  colour = c("aliceblue", "yellow", "green", 
             "turquoise", "orchid"),
  hobby = c("Hopping", "walking", "crocheting", 
            "", "running"),
  favourite_number = c(27, 4312, 11, 38, 27)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

*Remove this text (including the stars), and add your answer for Exercise 18 here.*
